# ── Font ─────────────────────────────────────────────────
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
bold_italic_font JetBrainsMono Nerd Font Bold Italic
font_size        11.0

# ── Cursor ───────────────────────────────────────────────
cursor                     #E0141C
cursor_text_color          #120304
cursor_shape               block
cursor_blink_interval      0.4

# ── Window ───────────────────────────────────────────────
window_padding_width       14
window_border_width        1px
active_border_color        #E0141C
inactive_border_color      #2F0507
background_opacity         0.92
background                 #120304
foreground                 #E8D5D9

# ── Cores Principais (Noir Vermelho — extraídas do wallpaper) ──
selection_background    #50080C
selection_foreground    #F6EAEE

url_color               #F9182A
url_style               curly

# Black (fundo quase-preto avermelhado)
color0 #120304
color8 #2F0507

# Red (Acento carmim)
color1 #8C0A10
color9 #E0141C

# Green (verde-acinzentado, contraste mínimo)
color2 #3A4034
color10 #6E7A58

# Yellow (bronze quente)
color3 #7A3A2A
color11 #D9A05C

# Blue (azul-acinzentado)
color4 #34354B
color12 #6A6A8E

# Magenta (rosa profundo da luz)
color5 #AD4159
color13 #EE6F89

# Cyan (cinza-lavanda)
color6 #786884
color14 #A08A9C

# White (off-white quente)
color7 #E8D5D9
color15 #F6EAEE

# Tab bar
active_tab_background   #2F0507
active_tab_foreground   #F9182A
inactive_tab_background #120304
inactive_tab_foreground #9A8A90
tab_bar_background      #0A0203
